INSERT INTO paese (nome, iso2, iso3, iso_numeric) VALUES
('Afghanistan','AF','AFG','004'),
('Albania','AL','ALB','008'),
('Algeria','DZ','DZA','012'),
('Andorra','AD','AND','020'),
('Angola','AO','AGO','024'),
('Anguilla','AI','AIA','660'),
('Antartide','AQ','ATA','010'),
('Antigua e Barbuda','AG','ATG','028'),
('Antille Francesi','BL','BLM','652'),
('Arabia Saudita','SA','SAU','682'),
('Argentina','AR','ARG','032'),
('Armenia','AM','ARM','051'),
('Aruba','AW','ABW','533'),
('Australia','AU','AUS','036'),
('Austria','AT','AUT','040'),
('Azerbaijan','AZ','AZE','031'),
('Bahamas','BS','BHS','044'),
('Bahrein','BH','BHR','048'),
('Bangladesh','BD','BGD','050'),
('Barbados','BB','BRB','052'),
('Belgio','BE','BEL','056'),
('Belize','BZ','BLZ','084'),
('Benin','BJ','BEN','204'),
('Bermuda','BM','BMU','060'),
('Bhutan','BT','BTN','064'),
('Bielorussia','BY','BLR','112'),
('Birmania','MM','MMR','104'),
('Bolivia','BO','BOL','068'),
('Bosnia ed Erzegovina','BA','BIH','070'),
('Botswana','BW','BWA','072'),
('Brasile','BR','BRA','076'),
('Brunei','BN','BRN','096'),
('Bulgaria','BG','BGR','100'),
('Burkina Faso','BF','BFA','854'),
('Burundi','BI','BDI','108'),
('Cambogia','KH','KHM','116'),
('Camerun','CM','CMR','120'),
('Canada','CA','CAN','124'),
('Capo Verde','CV','CPV','132'),
('Cechia','CZ','CZE','203'),
('Ciad','TD','TCD','148'),
('Cile','CL','CHL','152'),
('Cina','CN','CHN','156'),
('Cipro','CY','CYP','196'),
('Città del Vaticano','VA','VAT','336'),
('Colombia','CO','COL','170'),
('Comore','KM','COM','174'),
('Congo','CG','COG','178'),
('Congo (Rep. Dem.)','CD','COD','180'),
('Corea del Nord','KP','PRK','408'),
('Corea del Sud','KR','KOR','410'),
('Costa Rica','CR','CRI','188'),
('Costa d''Avorio','CI','CIV','384'),
('Croazia','HR','HRV','191'),
('Cuba','CU','CUB','192'),
('Curaçao','CW','CUW','531'),
('Danimarca','DK','DNK','208'),
('Dominica','DM','DMA','212'),
('Ecuador','EC','ECU','218'),
('Egitto','EG','EGY','818'),
('El Salvador','SV','SLV','222'),
('Emirati Arabi Uniti','AE','ARE','784'),
('Eritrea','ER','ERI','232'),
('Estonia','EE','EST','233'),
('Etiopia','ET','ETH','231'),
('Figi','FJ','FJI','242'),
('Filippine','PH','PHL','608'),
('Finlandia','FI','FIN','246'),
('Francia','FR','FRA','250'),
('Gabon','GA','GAB','266'),
('Gambia','GM','GMB','270'),
('Georgia','GE','GEO','268'),
('Georgia del Sud e Isole Sandwich Meridionali','GS','SGS','239'),
('Germania','DE','DEU','276'),
('Ghana','GH','GHA','288'),
('Giamaica','JM','JAM','388'),
('Giappone','JP','JPN','392'),
('Gibilterra','GI','GIB','292'),
('Gibuti','DJ','DJI','262'),
('Giordania','JO','JOR','400'),
('Grecia','GR','GRC','300'),
('Grenada','GD','GRD','308'),
('Groenlandia','GL','GRL','304'),
('Guadeloupa','GP','GLP','312'),
('Guam','GU','GUM','316'),
('Guatemala','GT','GTM','320'),
('Guernsey','GG','GGY','831'),
('Guinea','GN','GIN','324'),
('Guinea Equatoriale','GQ','GNQ','226'),
('Guinea-Bissau','GW','GNB','624'),
('Guyana','GY','GUY','328'),
('Guyana francese','GF','GUF','254'),
('Haiti','HT','HTI','332'),
('Honduras','HN','HND','340'),
('Hong Kong','HK','HKG','344'),
('India','IN','IND','356'),
('Indonesia','ID','IDN','360'),
('Iran','IR','IRN','364'),
('Iraq','IQ','IRQ','368'),
('Irlanda','IE','IRL','372'),
('Islanda','IS','ISL','352'),
('Isola Bouvet','BV','BVT','074'),
('Isola Norfolk','NF','NFK','574'),
('Isola di Jersey','JE','JEY','832'),
('Isola di Man','IM','IMN','833'),
('Isola di Natale','CX','CXR','162'),
('Isole Aland','AX','ALA','248'),
('Isole Cayman','KY','CYM','136'),
('Isole Cocos e Keeling','CC','CCK','166'),
('Isole Cook','CK','COK','184'),
('Isole Falkland o Isole Malvine','FK','FLK','238'),
('Isole Far Oer','FO','FRO','234'),
('Isole Heard e McDonald','HM','HMD','334'),
('Isole Marianne Settentrionali','MP','MNP','580'),
('Isole Marshall','MH','MHL','584'),
('Isole Pitcairn','PN','PCN','612'),
('Isole Salomone','SB','SLB','090'),
('Isole Tokelau','TK','TKL','772'),
('Isole Turks e Caicos','TC','TCA','796'),
('Isole Vergini Britanniche','VG','VGB','092'),
('Isole Vergini americane','VI','VIR','850'),
('Isole minori esterne degli Stati Uniti d''America','UM','UMI','581'),
('Israele','IL','ISR','376'),
('Italia','IT','ITA','380'),
('Kazakistan','KZ','KAZ','398'),
('Kenya','KE','KEN','404'),
('Kirghizistan','KG','KGZ','417'),
('Kiribati','KI','KIR','296'),
('Kosovo','XK','UNK',NULL),
('Kuwait','KW','KWT','414'),
('Laos','LA','LAO','418'),
('Lesotho','LS','LSO','426'),
('Lettonia','LV','LVA','428'),
('Libano','LB','LBN','422'),
('Liberia','LR','LBR','430'),
('Libia','LY','LBY','434'),
('Liechtenstein','LI','LIE','438'),
('Lituania','LT','LTU','440'),
('Lussemburgo','LU','LUX','442'),
('Macao','MO','MAC','446'),
('Macedonia del Nord','MK','MKD','807'),
('Madagascar','MG','MDG','450'),
('Malawi','MW','MWI','454'),
('Maldive','MV','MDV','462'),
('Malesia','MY','MYS','458'),
('Mali','ML','MLI','466'),
('Malta','MT','MLT','470'),
('Marocco','MA','MAR','504'),
('Martinica','MQ','MTQ','474'),
('Mauritania','MR','MRT','478'),
('Mauritius','MU','MUS','480'),
('Mayotte','YT','MYT','175'),
('Messico','MX','MEX','484'),
('Micronesia','FM','FSM','583'),
('Moldavia','MD','MDA','498'),
('Mongolia','MN','MNG','496'),
('Montenegro','ME','MNE','499'),
('Montserrat','MS','MSR','500'),
('Mozambico','MZ','MOZ','508'),
('Namibia','NA','NAM','516'),
('Nauru','NR','NRU','520'),
('Nepal','NP','NPL','524'),
('Nicaragua','NI','NIC','558'),
('Niger','NE','NER','562'),
('Nigeria','NG','NGA','566'),
('Niue','NU','NIU','570'),
('Norvegia','NO','NOR','578'),
('Nuova Caledonia','NC','NCL','540'),
('Nuova Zelanda','NZ','NZL','554'),
('Paesi Bassi','NL','NLD','528'),
('Paesi Bassi caraibici','BQ','BES','535'),
('Pakistan','PK','PAK','586'),
('Palau','PW','PLW','585'),
('Palestina','PS','PSE','275'),
('Panama','PA','PAN','591'),
('Papua Nuova Guinea','PG','PNG','598'),
('Paraguay','PY','PRY','600'),
('Perù','PE','PER','604'),
('Polinesia Francese','PF','PYF','258'),
('Polonia','PL','POL','616'),
('Porto Rico','PR','PRI','630'),
('Portogallo','PT','PRT','620'),
('Principato di Monaco','MC','MCO','492'),
('Qatar','QA','QAT','634'),
('Regno Unito','GB','GBR','826'),
('Repubblica Centrafricana','CF','CAF','140'),
('Repubblica Dominicana','DO','DOM','214'),
('Riunione','RE','REU','638'),
('Romania','RO','ROU','642'),
('Ruanda','RW','RWA','646'),
('Russia','RU','RUS','643'),
('Sahara Occidentale','EH','ESH','732'),
('Saint Kitts e Nevis','KN','KNA','659'),
('Saint Martin','MF','MAF','663'),
('Saint Vincent e Grenadine','VC','VCT','670'),
('Saint-Pierre e Miquelon','PM','SPM','666'),
('Samoa','WS','WSM','882'),
('Samoa Americane','AS','ASM','016'),
('San Marino','SM','SMR','674'),
('Sant''Elena, Ascensione e Tristan da Cunha','SH','SHN','654'),
('Santa Lucia','LC','LCA','662'),
('Senegal','SN','SEN','686'),
('Serbia','RS','SRB','688'),
('Seychelles','SC','SYC','690'),
('Sierra Leone','SL','SLE','694'),
('Singapore','SG','SGP','702'),
('Sint Maarten','SX','SXM','534'),
('Siria','SY','SYR','760'),
('Slovacchia','SK','SVK','703'),
('Slovenia','SI','SVN','705'),
('Somalia','SO','SOM','706'),
('Spagna','ES','ESP','724'),
('Sri Lanka','LK','LKA','144'),
('Stati Uniti d''America','US','USA','840'),
('Sud Africa','ZA','ZAF','710'),
('Sudan','SD','SDN','729'),
('Sudan del sud','SS','SSD','728'),
('Suriname','SR','SUR','740'),
('Svalbard e Jan Mayen','SJ','SJM','744'),
('Svezia','SE','SWE','752'),
('Svizzera','CH','CHE','756'),
('Swaziland','SZ','SWZ','748'),
('São Tomé e Príncipe','ST','STP','678'),
('Tagikistan','TJ','TJK','762'),
('Tailandia','TH','THA','764'),
('Taiwan','TW','TWN','158'),
('Tanzania','TZ','TZA','834'),
('Territori Francesi del Sud','TF','ATF','260'),
('Territorio britannico dell''oceano indiano','IO','IOT','086'),
('Timor Est','TL','TLS','626'),
('Togo','TG','TGO','768'),
('Tonga','TO','TON','776'),
('Trinidad e Tobago','TT','TTO','780'),
('Tunisia','TN','TUN','788'),
('Turchia','TR','TUR','792'),
('Turkmenistan','TM','TKM','795'),
('Tuvalu','TV','TUV','798'),
('Ucraina','UA','UKR','804'),
('Uganda','UG','UGA','800'),
('Ungheria','HU','HUN','348'),
('Uruguay','UY','URY','858'),
('Uzbekistan','UZ','UZB','860'),
('Vanuatu','VU','VUT','548'),
('Venezuela','VE','VEN','862'),
('Vietnam','VN','VNM','704'),
('Wallis e Futuna','WF','WLF','876'),
('Yemen','YE','YEM','887'),
('Zambia','ZM','ZMB','894'),
('Zimbabwe','ZW','ZWE','716'),
('oman','OM','OMN','512');
